In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
from datetime import time
from datetime import timedelta
import datetime as dt

In [2]:
df_logins = pd.read_json("logins.json")
df = pd.read_json("ultimate_data_challenge.json")

In [3]:
df

,city,trips_in_first_30_days,signup_date,avg_rating_of_driver,avg_surge,last_trip_date,phone,surge_pct,ultimate_black_user,weekday_pct,avg_dist,avg_rating_by_driver
0,King's Landing,4,2014-01-25,4.7,1.10,2014-06-17,iPhone,15.4,True,46.2,3.67,5.0
1,Astapor,0,2014-01-29,5.0,1.00,2014-05-05,Android,0.0,False,50.0,8.26,5.0
2,Astapor,3,2014-01-06,4.3,1.00,2014-01-07,iPhone,0.0,False,100.0,0.77,5.0
3,King's Landing,9,2014-01-10,4.6,1.14,2014-06-29,iPhone,20.0,True,80.0,2.36,4.9
4,Winterfell,14,2014-01-27,4.4,1.19,2014-03-15,Android,11.8,False,82.4,3.13,4.9
...,...,...,...,...,...,...,...,...,...,...,...,...
49995,King's Landing,0,2014-01-25,5.0,1.00,2014-06-05,iPhone,0.0,False,100.0,5.63,4.2
49996,Astapor,1,2014-01-24,NaN,1.00,2014-01-25,iPhone,0.0,False,0.0,0.00,4.0
49997,Winterfell,0,2014-01-31,5.0,1.00,2014-05-22,Android,0.0,True,100.0,3.86,5.0
49998,Astapor,2,2014-01-14,3.0,1.00,2014-01-15,iPhone,0.0,False,100.0,4.58,3.5
49999,Astapor,0,2014-01-18,NaN,1.00,2014-04-20,Android,0.0,False,0.0,3.49,5.0

In [4]:
df_logins

               login_time
0     1970-01-01 20:13:18
1     1970-01-01 20:16:10
2     1970-01-01 20:16:37
3     1970-01-01 20:16:36
4     1970-01-01 20:26:21
...                   ...
93137 1970-04-13 18:50:19
93138 1970-04-13 18:43:56
93139 1970-04-13 18:54:02
93140 1970-04-13 18:57:38
93141 1970-04-13 18:54:23

[93142 rows x 1 columns]

# Exploratory Data Analysis

In [5]:
type(df_logins["login_time"][0])

pandas._libs.tslibs.timestamps.Timestamp

In [6]:

login_time_df = pd.DataFrame()
login_time_df = df_logins['login_time'].copy()


login_time_df = login_time_df.to_frame()

In [7]:
#Extracting the date and time from the Timestamp
login_time_df['Date'] = login_time_df['login_time'].dt.date
login_time_df['Time'] = login_time_df['login_time'].dt.time

In [8]:
login_time_df

               login_time        Date      Time
0     1970-01-01 20:13:18  1970-01-01  20:13:18
1     1970-01-01 20:16:10  1970-01-01  20:16:10
2     1970-01-01 20:16:37  1970-01-01  20:16:37
3     1970-01-01 20:16:36  1970-01-01  20:16:36
4     1970-01-01 20:26:21  1970-01-01  20:26:21
...                   ...         ...       ...
93137 1970-04-13 18:50:19  1970-04-13  18:50:19
93138 1970-04-13 18:43:56  1970-04-13  18:43:56
93139 1970-04-13 18:54:02  1970-04-13  18:54:02
93140 1970-04-13 18:57:38  1970-04-13  18:57:38
93141 1970-04-13 18:54:23  1970-04-13  18:54:23

[93142 rows x 3 columns]

In [9]:
#Setting the start and end time with a dummy date of 1-Jan-100

start_time = dt.datetime(100,1,1,0,0)
end_time = dt.datetime(100,1,1,23,59)

print(start_time)

0100-01-01 00:00:00

In [10]:
#Initializing a dictionary to store the bins
time_bins = {1:start_time}

time_interval = start_time
counter = 1

#Setting the delta for 15 minutes
delta = timedelta(minutes = 15)

#Creating bins for each interval of date
while time_interval< end_time:
    time_bins[counter] = time_interval
    time_interval = time_interval+ dt.timedelta(minutes = 15)
    counter+=1

In [11]:
#Extracting only the time, thereby removing the dummy date
for k in time_bins.keys():
    time_bins[k] = time_bins[k].time()

In [12]:
time_bins

{1: datetime.time(0, 0),
 2: datetime.time(0, 15),
 3: datetime.time(0, 30),
 4: datetime.time(0, 45),
 5: datetime.time(1, 0),
 6: datetime.time(1, 15),
 7: datetime.time(1, 30),
 8: datetime.time(1, 45),
 9: datetime.time(2, 0),
 10: datetime.time(2, 15),
 11: datetime.time(2, 30),
 12: datetime.time(2, 45),
 13: datetime.time(3, 0),
 14: datetime.time(3, 15),
 15: datetime.time(3, 30),
 16: datetime.time(3, 45),
 17: datetime.time(4, 0),
 18: datetime.time(4, 15),
 19: datetime.time(4, 30),
 20: datetime.time(4, 45),
 21: datetime.time(5, 0),
 22: datetime.time(5, 15),
 23: datetime.time(5, 30),
 24: datetime.time(5, 45),
 25: datetime.time(6, 0),
 26: datetime.time(6, 15),
 27: datetime.time(6, 30),
 28: datetime.time(6, 45),
 29: datetime.time(7, 0),
 30: datetime.time(7, 15),
 31: datetime.time(7, 30),
 32: datetime.time(7, 45),
 33: datetime.time(8, 0),
 34: datetime.time(8, 15),
 35: datetime.time(8, 30),
 36: datetime.time(8, 45),
 37: datetime.time(9, 0),
 38: datetime.time(9, 15),
 39: datetime.time(9, 30),
 40: datetime.time(9, 45),
 41: datetime.time(10, 0),
 42: datetime.time(10, 15),
 43: datetime.time(10, 30),
 44: datetime.time(10, 45),
 45: datetime.time(11, 0),
 46: datetime.time(11, 15),
 47: datetime.time(11, 30),
 48: datetime.time(11, 45),
 49: datetime.time(12, 0),
 50: datetime.time(12, 15),
 51: datetime.time(12, 30),
 52: datetime.time(12, 45),
 53: datetime.time(13, 0),
 54: datetime.time(13, 15),
 55: datetime.time(13, 30),
 56: datetime.time(13, 45),
 57: datetime.time(14, 0),
 58: datetime.time(14, 15),
 59: datetime.time(14, 30),
 60: datetime.time(14, 45),
 61: datetime.time(15, 0),
 62: datetime.time(15, 15),
 63: datetime.time(15, 30),
 64: datetime.time(15, 45),
 65: datetime.time(16, 0),
 66: datetime.time(16, 15),
 67: datetime.time(16, 30),
 68: datetime.time(16, 45),
 69: datetime.time(17, 0),
 70: datetime.time(17, 15),
 71: datetime.time(17, 30),
 72: datetime.time(17, 45),
 73: datetime.time(18, 0),
 74: datetime.time(18, 15),
 75: datetime.time(18, 30),
 76: datetime.time(18, 45),
 77: datetime.time(19, 0),
 78: datetime.time(19, 15),
 79: datetime.time(19, 30),
 80: datetime.time(19, 45),
 81: datetime.time(20, 0),
 82: datetime.time(20, 15),
 83: datetime.time(20, 30),
 84: datetime.time(20, 45),
 85: datetime.time(21, 0),
 86: datetime.time(21, 15),
 87: datetime.time(21, 30),
 88: datetime.time(21, 45),
 89: datetime.time(22, 0),
 90: datetime.time(22, 15),
 91: datetime.time(22, 30),
 92: datetime.time(22, 45),
 93: datetime.time(23, 0),
 94: datetime.time(23, 15),
 95: datetime.time(23, 30),
 96: datetime.time(23, 45)}

In [13]:
#Swapping the keys and values
flip_time_bins = {value:key for key, value in time_bins.items()}

In [14]:
flip_time_bins

{datetime.time(0, 0): 1,
 datetime.time(0, 15): 2,
 datetime.time(0, 30): 3,
 datetime.time(0, 45): 4,
 datetime.time(1, 0): 5,
 datetime.time(1, 15): 6,
 datetime.time(1, 30): 7,
 datetime.time(1, 45): 8,
 datetime.time(2, 0): 9,
 datetime.time(2, 15): 10,
 datetime.time(2, 30): 11,
 datetime.time(2, 45): 12,
 datetime.time(3, 0): 13,
 datetime.time(3, 15): 14,
 datetime.time(3, 30): 15,
 datetime.time(3, 45): 16,
 datetime.time(4, 0): 17,
 datetime.time(4, 15): 18,
 datetime.time(4, 30): 19,
 datetime.time(4, 45): 20,
 datetime.time(5, 0): 21,
 datetime.time(5, 15): 22,
 datetime.time(5, 30): 23,
 datetime.time(5, 45): 24,
 datetime.time(6, 0): 25,
 datetime.time(6, 15): 26,
 datetime.time(6, 30): 27,
 datetime.time(6, 45): 28,
 datetime.time(7, 0): 29,
 datetime.time(7, 15): 30,
 datetime.time(7, 30): 31,
 datetime.time(7, 45): 32,
 datetime.time(8, 0): 33,
 datetime.time(8, 15): 34,
 datetime.time(8, 30): 35,
 datetime.time(8, 45): 36,
 datetime.time(9, 0): 37,
 datetime.time(9, 15): 38,
 datetime.time(9, 30): 39,
 datetime.time(9, 45): 40,
 datetime.time(10, 0): 41,
 datetime.time(10, 15): 42,
 datetime.time(10, 30): 43,
 datetime.time(10, 45): 44,
 datetime.time(11, 0): 45,
 datetime.time(11, 15): 46,
 datetime.time(11, 30): 47,
 datetime.time(11, 45): 48,
 datetime.time(12, 0): 49,
 datetime.time(12, 15): 50,
 datetime.time(12, 30): 51,
 datetime.time(12, 45): 52,
 datetime.time(13, 0): 53,
 datetime.time(13, 15): 54,
 datetime.time(13, 30): 55,
 datetime.time(13, 45): 56,
 datetime.time(14, 0): 57,
 datetime.time(14, 15): 58,
 datetime.time(14, 30): 59,
 datetime.time(14, 45): 60,
 datetime.time(15, 0): 61,
 datetime.time(15, 15): 62,
 datetime.time(15, 30): 63,
 datetime.time(15, 45): 64,
 datetime.time(16, 0): 65,
 datetime.time(16, 15): 66,
 datetime.time(16, 30): 67,
 datetime.time(16, 45): 68,
 datetime.time(17, 0): 69,
 datetime.time(17, 15): 70,
 datetime.time(17, 30): 71,
 datetime.time(17, 45): 72,
 datetime.time(18, 0): 73,
 datetime.time(18, 15): 74,
 datetime.time(18, 30): 75,
 datetime.time(18, 45): 76,
 datetime.time(19, 0): 77,
 datetime.time(19, 15): 78,
 datetime.time(19, 30): 79,
 datetime.time(19, 45): 80,
 datetime.time(20, 0): 81,
 datetime.time(20, 15): 82,
 datetime.time(20, 30): 83,
 datetime.time(20, 45): 84,
 datetime.time(21, 0): 85,
 datetime.time(21, 15): 86,
 datetime.time(21, 30): 87,
 datetime.time(21, 45): 88,
 datetime.time(22, 0): 89,
 datetime.time(22, 15): 90,
 datetime.time(22, 30): 91,
 datetime.time(22, 45): 92,
 datetime.time(23, 0): 93,
 datetime.time(23, 15): 94,
 datetime.time(23, 30): 95,
 datetime.time(23, 45): 96}

## What to do next

Figure out a way to assign a value of bins and add it to the dataframe.

In [15]:
bin_dict = {}
counter =0
for login_time in login_time_df["Time"]:
    if login_time.minute >= 0 and login_time.minute<15:
        login_time = time(login_time.hour,15,0)
        bin_dict[counter] = login_time
        counter +=1
        continue
    if login_time.minute >= 15 and login_time.minute <30:
        login_time = time(login_time.hour,30,0)
        bin_dict[counter] = login_time
        counter +=1
        continue
    if login_time.minute >= 30 and login_time.minute <45:
        login_time = time(login_time.hour,45,0)
        bin_dict[counter] = login_time
        counter +=1
        continue
    if login_time.minute >= 45 and login_time.minute <60:
        if login_time.hour == 23:
            login_time = time( 0,0,0)
        else:
            login_time = time(login_time.hour +1 ,0,0)
    bin_dict[counter] = login_time
    counter +=1

In [16]:
bin_dict

{0: datetime.time(20, 15),
 1: datetime.time(20, 30),
 2: datetime.time(20, 30),
 3: datetime.time(20, 30),
 4: datetime.time(20, 30),
 5: datetime.time(20, 30),
 6: datetime.time(20, 15),
 7: datetime.time(20, 45),
 8: datetime.time(20, 45),
 9: datetime.time(21, 0),
 10: datetime.time(20, 30),
 11: datetime.time(20, 45),
 12: datetime.time(20, 45),
 13: datetime.time(20, 45),
 14: datetime.time(20, 45),
 15: datetime.time(20, 45),
 16: datetime.time(20, 45),
 17: datetime.time(20, 45),
 18: datetime.time(21, 0),
 19: datetime.time(21, 0),
 20: datetime.time(21, 0),
 21: datetime.time(21, 0),
 22: datetime.time(21, 0),
 23: datetime.time(21, 0),
 24: datetime.time(21, 30),
 25: datetime.time(21, 15),
 26: datetime.time(21, 30),
 27: datetime.time(21, 30),
 28: datetime.time(21, 30),
 29: datetime.time(22, 0),
 30: datetime.time(22, 0),
 31: datetime.time(22, 0),
 32: datetime.time(22, 15),
 33: datetime.time(22, 15),
 34: datetime.time(22, 0),
 35: datetime.time(22, 15),
 36: datetime.time(22, 15),
 37: datetime.time(22, 15),
 38: datetime.time(22, 15),
 39: datetime.time(22, 15),
 40: datetime.time(22, 15),
 41: datetime.time(22, 30),
 42: datetime.time(22, 30),
 43: datetime.time(22, 30),
 44: datetime.time(22, 15),
 45: datetime.time(22, 30),
 46: datetime.time(22, 30),
 47: datetime.time(22, 30),
 48: datetime.time(22, 30),
 49: datetime.time(22, 30),
 50: datetime.time(22, 45),
 51: datetime.time(23, 15),
 52: datetime.time(23, 0),
 53: datetime.time(23, 15),
 54: datetime.time(23, 15),
 55: datetime.time(23, 15),
 56: datetime.time(23, 15),
 57: datetime.time(23, 15),
 58: datetime.time(23, 15),
 59: datetime.time(23, 15),
 60: datetime.time(23, 15),
 61: datetime.time(23, 0),
 62: datetime.time(23, 15),
 63: datetime.time(23, 15),
 64: datetime.time(23, 15),
 65: datetime.time(23, 15),
 66: datetime.time(23, 0),
 67: datetime.time(23, 15),
 68: datetime.time(23, 30),
 69: datetime.time(23, 15),
 70: datetime.time(23, 30),
 71: datetime.time(23, 15),
 72: datetime.time(23, 30),
 73: datetime.time(23, 30),
 74: datetime.time(23, 30),
 75: datetime.time(23, 30),
 76: datetime.time(23, 30),
 77: datetime.time(23, 30),
 78: datetime.time(23, 45),
 79: datetime.time(23, 45),
 80: datetime.time(23, 30),
 81: datetime.time(23, 30),
 82: datetime.time(23, 30),
 83: datetime.time(23, 30),
 84: datetime.time(23, 45),
 85: datetime.time(23, 45),
 86: datetime.time(23, 45),
 87: datetime.time(23, 45),
 88: datetime.time(23, 45),
 89: datetime.time(0, 0),
 90: datetime.time(23, 45),
 91: datetime.time(23, 45),
 92: datetime.time(23, 45),
 93: datetime.time(23, 45),
 94: datetime.time(0, 0),
 95: datetime.time(0, 0),
 96: datetime.time(0, 0),
 97: datetime.time(23, 30),
 98: datetime.time(0, 0),
 99: datetime.time(23, 45),
 100: datetime.time(23, 45),
 101: datetime.time(0, 0),
 102: datetime.time(23, 45),
 103: datetime.time(0, 0),
 104: datetime.time(0, 0),
 105: datetime.time(0, 0),
 106: datetime.time(0, 0),
 107: datetime.time(0, 0),
 108: datetime.time(0, 0),
 109: datetime.time(0, 0),
 110: datetime.time(0, 15),
 111: datetime.time(0, 0),
 112: datetime.time(0, 0),
 113: datetime.time(0, 15),
 114: datetime.time(0, 15),
 115: datetime.time(0, 15),
 116: datetime.time(0, 15),
 117: datetime.time(0, 15),
 118: datetime.time(0, 15),
 119: datetime.time(0, 15),
 120: datetime.time(0, 15),
 121: datetime.time(0, 15),
 122: datetime.time(0, 30),
 123: datetime.time(0, 30),
 124: datetime.time(0, 30),
 125: datetime.time(0, 30),
 126: datetime.time(0, 30),
 127: datetime.time(0, 30),
 128: datetime.time(0, 30),
 129: datetime.time(0, 30),
 130: datetime.time(0, 30),
 131: datetime.time(0, 30),
 132: datetime.time(0, 45),
 133: datetime.time(0, 45),
 134: datetime.time(0, 30),
 135: datetime.time(0, 30),
 136: datetime.time(0, 45),
 137: datetime.time(0, 30),
 138: datetime.time(0, 30),
 139: datetime.time(0, 30),
 140: datetime.time(0, 45),
 141: datetime.time(0, 30),
 142: datetime.time(0, 30),
 143: datetime.time(0, 45),
 144: datetime.time(0, 45),
 145: datetime.time(0, 30),
 146: datetime.time(1, 0),
 147: datetime.time(0, 45),
 148: datetime.time(1, 0),
 149: datetime.time(0, 45),
 150: datetime.time(0, 45),
 151: datetime.time(1, 0),
 152: datetime.time(0, 45),
 153: datetime.time(0, 45),
 154: datetime.time(1, 0),
 155: datetime.time(1, 0),
 156: datetime.time(1, 0),
 157: datetime.time(1, 0),
 158: datetime.time(0, 45),
 159: datetime.time(1, 0),
 160: datetime.time(1, 15),
 161: datetime.time(1, 0),
 162: datetime.time(1, 0),
 163: datetime.time(1, 0),
 164: datetime.time(1, 0),
 165: datetime.time(1, 15),
 166: datetime.time(1, 0),
 167: datetime.time(1, 15),
 168: datetime.time(1, 15),
 169: datetime.time(1, 15),
 170: datetime.time(1, 30),
 171: datetime.time(1, 30),
 172: datetime.time(1, 15),
 173: datetime.time(1, 15),
 174: datetime.time(1, 15),
 175: datetime.time(1, 30),
 176: datetime.time(1, 15),
 177: datetime.time(1, 30),
 178: datetime.time(1, 30),
 179: datetime.time(1, 45),
 180: datetime.time(1, 30),
 181: datetime.time(1, 45),
 182: datetime.time(1, 30),
 183: datetime.time(1, 30),
 184: datetime.time(1, 45),
 185: datetime.time(1, 45),
 186: datetime.time(1, 45),
 187: datetime.time(1, 45),
 188: datetime.time(1, 45),
 189: datetime.time(1, 45),
 190: datetime.time(1, 45),
 191: datetime.time(2, 0),
 192: datetime.time(1, 45),
 193: datetime.time(2, 0),
 194: datetime.time(2, 0),
 195: datetime.time(2, 0),
 196: datetime.time(2, 0),
 197: datetime.time(2, 15),
 198: datetime.time(2, 15),
 199: datetime.time(2, 15),
 200: datetime.time(2, 15),
 201: datetime.time(2, 15),
 202: datetime.time(2, 0),
 203: datetime.time(2, 15),
 204: datetime.time(2, 15),
 205: datetime.time(2, 30),
 206: datetime.time(2, 30),
 207: datetime.time(2, 30),
 208: datetime.time(2, 30),
 209: datetime.time(2, 30),
 210: datetime.time(2, 30),
 211: datetime.time(2, 30),
 212: datetime.time(2, 30),
 213: datetime.time(2, 30),
 214: datetime.time(2, 30),
 215: datetime.time(2, 45),
 216: datetime.time(2, 30),
 217: datetime.time(2, 30),
 218: datetime.time(2, 30),
 219: datetime.time(2, 45),
 220: datetime.time(2, 45),
 221: datetime.time(2, 30),
 222: datetime.time(2, 45),
 223: datetime.time(2, 30),
 224: datetime.time(2, 45),
 225: datetime.time(2, 30),
 226: datetime.time(2, 45),
 227: datetime.time(2, 45),
 228: datetime.time(2, 30),
 229: datetime.time(2, 45),
 230: datetime.time(2, 30),
 231: datetime.time(2, 45),
 232: datetime.time(2, 45),
 233: datetime.time(3, 0),
 234: datetime.time(2, 45),
 235: datetime.time(2, 45),
 236: datetime.time(3, 0),
 237: datetime.time(3, 0),
 238: datetime.time(3, 0),
 239: datetime.time(3, 0),
 240: datetime.time(3, 15),
 241: datetime.time(3, 0),
 242: datetime.time(3, 15),
 243: datetime.time(3, 15),
 244: datetime.time(3, 15),
 245: datetime.time(3, 15),
 246: datetime.time(3, 15),
 247: datetime.time(3, 15),
 248: datetime.time(3, 15),
 249: datetime.time(3, 30),
 250: datetime.time(3, 30),
 251: datetime.time(3, 30),
 252: datetime.time(3, 15),
 253: datetime.time(3, 15),
 254: datetime.time(3, 15),
 255: datetime.time(3, 30),
 256: datetime.time(3, 15),
 257: datetime.time(3, 30),
 258: datetime.time(3, 45),
 259: datetime.time(3, 45),
 260: datetime.time(3, 45),
 261: datetime.time(3, 45),
 262: datetime.time(3, 45),
 263: datetime.time(3, 45),
 264: datetime.time(4, 0),
 265: datetime.time(4, 0),
 266: datetime.time(4, 0),
 267: datetime.time(4, 0),
 268: datetime.time(4, 0),
 269: datetime.time(4, 15),
 270: datetime.time(4, 15),
 271: datetime.time(4, 45),
 272: datetime.time(4, 45),
 273: datetime.time(5, 0),
 274: datetime.time(4, 45),
 275: datetime.time(4, 45),
 276: datetime.time(4, 45),
 277: datetime.time(5, 15),
 278: datetime.time(5, 15),
 279: datetime.time(5, 0),
 280: datetime.time(5, 15),
 281: datetime.time(5, 30),
 282: datetime.time(5, 15),
 283: datetime.time(5, 30),
 284: datetime.time(5, 15),
 285: datetime.time(5, 30),
 286: datetime.time(5, 30),
 287: datetime.time(5, 45),
 288: datetime.time(6, 0),
 289: datetime.time(6, 15),
 290: datetime.time(7, 0),
 291: datetime.time(6, 45),
 292: datetime.time(6, 45),
 293: datetime.time(7, 0),
 294: datetime.time(7, 0),
 295: datetime.time(7, 0),
 296: datetime.time(7, 15),
 297: datetime.time(7, 15),
 298: datetime.time(7, 30),
 299: datetime.time(7, 15),
 300: datetime.time(7, 45),
 301: datetime.time(8, 0),
 302: datetime.time(8, 15),
 303: datetime.time(8, 15),
 304: datetime.time(8, 30),
 305: datetime.time(8, 15),
 306: datetime.time(8, 45),
 307: datetime.time(8, 45),
 308: datetime.time(8, 45),
 309: datetime.time(9, 0),
 310: datetime.time(9, 15),
 311: datetime.time(9, 30),
 312: datetime.time(9, 15),
 313: datetime.time(9, 15),
 314: datetime.time(9, 45),
 315: datetime.time(9, 45),
 316: datetime.time(9, 45),
 317: datetime.time(9, 45),
 318: datetime.time(9, 45),
 319: datetime.time(9, 45),
 320: datetime.time(10, 0),
 321: datetime.time(10, 15),
 322: datetime.time(10, 0),
 323: datetime.time(10, 15),
 324: datetime.time(10, 15),
 325: datetime.time(10, 15),
 326: datetime.time(10, 15),
 327: datetime.time(10, 15),
 328: datetime.time(10, 15),
 329: datetime.time(10, 30),
 330: datetime.time(10, 30),
 331: datetime.time(10, 30),
 332: datetime.time(10, 30),
 333: datetime.time(10, 30),
 334: datetime.time(10, 30),
 335: datetime.time(10, 30),
 336: datetime.time(10, 45),
 337: datetime.time(10, 30),
 338: datetime.time(10, 45),
 339: datetime.time(10, 45),
 340: datetime.time(10, 45),
 341: datetime.time(10, 45),
 342: datetime.time(10, 45),
 343: datetime.time(10, 45),
 344: datetime.time(11, 0),
 345: datetime.time(10, 45),
 346: datetime.time(11, 0),
 347: datetime.time(11, 0),
 348: datetime.time(11, 0),
 349: datetime.time(11, 15),
 350: datetime.time(11, 15),
 351: datetime.time(11, 15),
 352: datetime.time(11, 15),
 353: datetime.time(11, 15),
 354: datetime.time(11, 0),
 355: datetime.time(11, 15),
 356: datetime.time(11, 15),
 357: datetime.time(11, 15),
 358: datetime.time(11, 30),
 359: datetime.time(11, 30),
 360: datetime.time(11, 15),
 361: datetime.time(11, 30),
 362: datetime.time(11, 30),
 363: datetime.time(11, 30),
 364: datetime.time(11, 30),
 365: datetime.time(11, 30),
 366: datetime.time(11, 45),
 367: datetime.time(11, 45),
 368: datetime.time(11, 30),
 369: datetime.time(11, 30),
 370: datetime.time(11, 45),
 371: datetime.time(11, 45),
 372: datetime.time(11, 45),
 373: datetime.time(11, 45),
 374: datetime.time(11, 30),
 375: datetime.time(11, 30),
 376: datetime.time(11, 30),
 377: datetime.time(11, 45),
 378: datetime.time(11, 45),
 379: datetime.time(11, 45),
 380: datetime.time(11, 45),
 381: datetime.time(11, 45),
 382: datetime.time(11, 45),
 383: datetime.time(11, 45),
 384: datetime.time(11, 45),
 385: datetime.time(11, 45),
 386: datetime.time(12, 0),
 387: datetime.time(11, 45),
 388: datetime.time(12, 0),
 389: datetime.time(11, 45),
 390: datetime.time(12, 0),
 391: datetime.time(11, 45),
 392: datetime.time(12, 0),
 393: datetime.time(12, 0),
 394: datetime.time(12, 0),
 395: datetime.time(12, 0),
 396: datetime.time(12, 0),
 397: datetime.time(12, 0),
 398: datetime.time(12, 15),
 399: datetime.time(12, 15),
 400: datetime.time(12, 0),
 401: datetime.time(12, 15),
 402: datetime.time(12, 0),
 403: datetime.time(12, 0),
 404: datetime.time(12, 15),
 405: datetime.time(12, 0),
 406: datetime.time(12, 15),
 407: datetime.time(12, 15),
 408: datetime.time(12, 15),
 409: datetime.time(12, 15),
 410: datetime.time(12, 0),
 411: datetime.time(12, 15),
 412: datetime.time(12, 15),
 413: datetime.time(12, 15),
 414: datetime.time(12, 30),
 415: datetime.time(12, 30),
 416: datetime.time(12, 15),
 417: datetime.time(12, 30),
 418: datetime.time(12, 15),
 419: datetime.time(12, 30),
 420: datetime.time(12, 15),
 421: datetime.time(12, 15),
 422: datetime.time(12, 30),
 423: datetime.time(12, 30),
 424: datetime.time(12, 30),
 425: datetime.time(12, 30),
 426: datetime.time(12, 30),
 427: datetime.time(12, 30),
 428: datetime.time(12, 30),
 429: datetime.time(12, 45),
 430: datetime.time(12, 30),
 431: datetime.time(12, 45),
 432: datetime.time(12, 30),
 433: datetime.time(12, 30),
 434: datetime.time(12, 30),
 435: datetime.time(12, 30),
 436: datetime.time(12, 45),
 437: datetime.time(12, 45),
 438: datetime.time(12, 45),
 439: datetime.time(12, 45),
 440: datetime.time(12, 45),
 441: datetime.time(12, 45),
 442: datetime.time(12, 30),
 443: datetime.time(13, 0),
 444: datetime.time(12, 45),
 445: datetime.time(12, 45),
 446: datetime.time(13, 0),
 447: datetime.time(12, 45),
 448: datetime.time(12, 45),
 449: datetime.time(13, 0),
 450: datetime.time(13, 0),
 451: datetime.time(12, 45),
 452: datetime.time(12, 45),
 453: datetime.time(13, 0),
 454: datetime.time(13, 0),
 455: datetime.time(13, 0),
 456: datetime.time(13, 0),
 457: datetime.time(13, 15),
 458: datetime.time(13, 15),
 459: datetime.time(13, 15),
 460: datetime.time(13, 15),
 461: datetime.time(13, 30),
 462: datetime.time(13, 30),
 463: datetime.time(13, 30),
 464: datetime.time(13, 30),
 465: datetime.time(13, 45),
 466: datetime.time(13, 30),
 467: datetime.time(13, 45),
 468: datetime.time(13, 45),
 469: datetime.time(13, 45),
 470: datetime.time(13, 45),
 471: datetime.time(13, 45),
 472: datetime.time(13, 45),
 473: datetime.time(13, 45),
 474: datetime.time(14, 0),
 475: datetime.time(13, 45),
 476: datetime.time(14, 0),
 477: datetime.time(14, 15),
 478: datetime.time(14, 15),
 479: datetime.time(14, 15),
 480: datetime.time(14, 15),
 481: datetime.time(14, 15),
 482: datetime.time(14, 30),
 483: datetime.time(14, 15),
 484: datetime.time(14, 30),
 485: datetime.time(14, 30),
 486: datetime.time(14, 15),
 487: datetime.time(14, 30),
 488: datetime.time(14, 30),
 489: datetime.time(14, 30),
 490: datetime.time(14, 45),
 491: datetime.time(14, 45),
 492: datetime.time(14, 45),
 493: datetime.time(15, 0),
 494: datetime.time(15, 0),
 495: datetime.time(14, 45),
 496: datetime.time(15, 0),
 497: datetime.time(14, 45),
 498: datetime.time(15, 15),
 499: datetime.time(15, 0),
 500: datetime.time(15, 0),
 501: datetime.time(15, 0),
 502: datetime.time(15, 0),
 503: datetime.time(15, 15),
 504: datetime.time(15, 15),
 505: datetime.time(15, 30),
 506: datetime.time(15, 15),
 507: datetime.time(15, 30),
 508: datetime.time(15, 15),
 509: datetime.time(15, 30),
 510: datetime.time(15, 30),
 511: datetime.time(15, 45),
 512: datetime.time(15, 30),
 513: datetime.time(15, 45),
 514: datetime.time(16, 0),
 515: datetime.time(16, 0),
 516: datetime.time(16, 0),
 517: datetime.time(16, 0),
 518: datetime.time(16, 15),
 519: datetime.time(16, 15),
 520: datetime.time(16, 15),
 521: datetime.time(16, 15),
 522: datetime.time(16, 15),
 523: datetime.time(16, 15),
 524: datetime.time(16, 15),
 525: datetime.time(16, 30),
 526: datetime.time(16, 30),
 527: datetime.time(16, 30),
 528: datetime.time(16, 45),
 529: datetime.time(16, 45),
 530: datetime.time(16, 45),
 531: datetime.time(16, 45),
 532: datetime.time(17, 0),
 533: datetime.time(17, 0),
 534: datetime.time(17, 0),
 535: datetime.time(17, 0),
 536: datetime.time(17, 0),
 537: datetime.time(17, 15),
 538: datetime.time(17, 15),
 539: datetime.time(17, 15),
 540: datetime.time(17, 15),
 541: datetime.time(17, 30),
 542: datetime.time(17, 15),
 543: datetime.time(17, 15),
 544: datetime.time(17, 30),
 545: datetime.time(17, 30),
 546: datetime.time(17, 30),
 547: datetime.time(17, 30),
 548: datetime.time(17, 45),
 549: datetime.time(17, 45),
 550: datetime.time(18, 0),
 551: datetime.time(18, 0),
 552: datetime.time(18, 0),
 553: datetime.time(18, 0),
 554: datetime.time(18, 30),
 555: datetime.time(18, 45),
 556: datetime.time(18, 30),
 557: datetime.time(18, 30),
 558: datetime.time(18, 45),
 559: datetime.time(18, 45),
 560: datetime.time(19, 0),
 561: datetime.time(19, 0),
 562: datetime.time(19, 0),
 563: datetime.time(19, 15),
 564: datetime.time(19, 15),
 565: datetime.time(19, 15),
 566: datetime.time(19, 15),
 567: datetime.time(19, 0),
 568: datetime.time(19, 15),
 569: datetime.time(19, 15),
 570: datetime.time(19, 15),
 571: datetime.time(19, 15),
 572: datetime.time(19, 30),
 573: datetime.time(19, 30),
 574: datetime.time(19, 45),
 575: datetime.time(19, 45),
 576: datetime.time(19, 30),
 577: datetime.time(19, 45),
 578: datetime.time(19, 30),
 579: datetime.time(19, 30),
 580: datetime.time(19, 45),
 581: datetime.time(19, 45),
 582: datetime.time(20, 0),
 583: datetime.time(20, 0),
 584: datetime.time(20, 0),
 585: datetime.time(20, 0),
 586: datetime.time(20, 0),
 587: datetime.time(20, 15),
 588: datetime.time(20, 0),
 589: datetime.time(20, 15),
 590: datetime.time(20, 15),
 591: datetime.time(20, 15),
 592: datetime.time(20, 30),
 593: datetime.time(20, 15),
 594: datetime.time(20, 15),
 595: datetime.time(20, 30),
 596: datetime.time(20, 30),
 597: datetime.time(20, 30),
 598: datetime.time(20, 45),
 599: datetime.time(20, 30),
 600: datetime.time(20, 15),
 601: datetime.time(20, 45),
 602: datetime.time(20, 30),
 603: datetime.time(20, 30),
 604: datetime.time(20, 45),
 605: datetime.time(20, 45),
 606: datetime.time(20, 30),
 607: datetime.time(20, 45),
 608: datetime.time(20, 30),
 609: datetime.time(20, 45),
 610: datetime.time(20, 45),
 611: datetime.time(20, 45),
 612: datetime.time(20, 45),
 613: datetime.time(20, 45),
 614: datetime.time(20, 45),
 615: datetime.time(20, 45),
 616: datetime.time(21, 0),
 617: datetime.time(20, 45),
 618: datetime.time(21, 0),
 619: datetime.time(21, 0),
 620: datetime.time(21, 0),
 621: datetime.time(21, 0),
 622: datetime.time(21, 0),
 623: datetime.time(21, 0),
 624: datetime.time(21, 0),
 625: datetime.time(21, 0),
 626: datetime.time(21, 0),
 627: datetime.time(21, 0),
 628: datetime.time(21, 0),
 629: datetime.time(21, 0),
 630: datetime.time(21, 15),
 631: datetime.time(21, 15),
 632: datetime.time(21, 15),
 633: datetime.time(21, 15),
 634: datetime.time(21, 30),
 635: datetime.time(21, 15),
 636: datetime.time(21, 30),
 637: datetime.time(21, 15),
 638: datetime.time(21, 30),
 639: datetime.time(21, 30),
 640: datetime.time(21, 30),
 641: datetime.time(21, 30),
 642: datetime.time(21, 30),
 643: datetime.time(21, 30),
 644: datetime.time(21, 30),
 645: datetime.time(21, 45),
 646: datetime.time(21, 45),
 647: datetime.time(21, 30),
 648: datetime.time(21, 45),
 649: datetime.time(21, 45),
 650: datetime.time(21, 45),
 651: datetime.time(21, 45),
 652: datetime.time(21, 45),
 653: datetime.time(22, 0),
 654: datetime.time(22, 0),
 655: datetime.time(22, 0),
 656: datetime.time(22, 0),
 657: datetime.time(22, 0),
 658: datetime.time(22, 0),
 659: datetime.time(21, 45),
 660: datetime.time(22, 0),
 661: datetime.time(21, 45),
 662: datetime.time(21, 45),
 663: datetime.time(21, 45),
 664: datetime.time(22, 0),
 665: datetime.time(22, 0),
 666: datetime.time(22, 0),
 667: datetime.time(22, 0),
 668: datetime.time(22, 0),
 669: datetime.time(22, 15),
 670: datetime.time(22, 0),
 671: datetime.time(22, 15),
 672: datetime.time(22, 15),
 673: datetime.time(22, 0),
 674: datetime.time(22, 15),
 675: datetime.time(22, 15),
 676: datetime.time(22, 15),
 677: datetime.time(22, 15),
 678: datetime.time(22, 15),
 679: datetime.time(22, 15),
 680: datetime.time(22, 15),
 681: datetime.time(22, 15),
 682: datetime.time(22, 15),
 683: datetime.time(22, 30),
 684: datetime.time(22, 15),
 685: datetime.time(22, 30),
 686: datetime.time(22, 30),
 687: datetime.time(22, 30),
 688: datetime.time(22, 15),
 689: datetime.time(22, 30),
 690: datetime.time(22, 30),
 691: datetime.time(22, 30),
 692: datetime.time(22, 15),
 693: datetime.time(22, 30),
 694: datetime.time(22, 30),
 695: datetime.time(22, 30),
 696: datetime.time(22, 30),
 697: datetime.time(22, 30),
 698: datetime.time(22, 30),
 699: datetime.time(22, 30),
 700: datetime.time(22, 30),
 701: datetime.time(22, 45),
 702: datetime.time(22, 45),
 703: datetime.time(22, 45),
 704: datetime.time(22, 30),
 705: datetime.time(22, 45),

In [17]:
login_time_df["Bin"] = bin_dict.values()

In [18]:
login_time_df

               login_time        Date      Time       Bin
0     1970-01-01 20:13:18  1970-01-01  20:13:18  20:15:00
1     1970-01-01 20:16:10  1970-01-01  20:16:10  20:30:00
2     1970-01-01 20:16:37  1970-01-01  20:16:37  20:30:00
3     1970-01-01 20:16:36  1970-01-01  20:16:36  20:30:00
4     1970-01-01 20:26:21  1970-01-01  20:26:21  20:30:00
...                   ...         ...       ...       ...
93137 1970-04-13 18:50:19  1970-04-13  18:50:19  19:00:00
93138 1970-04-13 18:43:56  1970-04-13  18:43:56  18:45:00
93139 1970-04-13 18:54:02  1970-04-13  18:54:02  19:00:00
93140 1970-04-13 18:57:38  1970-04-13  18:57:38  19:00:00
93141 1970-04-13 18:54:23  1970-04-13  18:54:23  19:00:00

[93142 rows x 4 columns]

In [41]:
bins = login_time_df["Bin"].unique()
print(bins)

[datetime.time(20, 15) datetime.time(20, 30) datetime.time(20, 45)
 datetime.time(21, 0) datetime.time(21, 30) datetime.time(21, 15)
 datetime.time(22, 0) datetime.time(22, 15) datetime.time(22, 30)
 datetime.time(22, 45) datetime.time(23, 15) datetime.time(23, 0)
 datetime.time(23, 30) datetime.time(23, 45) datetime.time(0, 0)
 datetime.time(0, 15) datetime.time(0, 30) datetime.time(0, 45)
 datetime.time(1, 0) datetime.time(1, 15) datetime.time(1, 30)
 datetime.time(1, 45) datetime.time(2, 0) datetime.time(2, 15)
 datetime.time(2, 30) datetime.time(2, 45) datetime.time(3, 0)
 datetime.time(3, 15) datetime.time(3, 30) datetime.time(3, 45)
 datetime.time(4, 0) datetime.time(4, 15) datetime.time(4, 45)
 datetime.time(5, 0) datetime.time(5, 15) datetime.time(5, 30)
 datetime.time(5, 45) datetime.time(6, 0) datetime.time(6, 15)
 datetime.time(7, 0) datetime.time(6, 45) datetime.time(7, 15)
 datetime.time(7, 30) datetime.time(7, 45) datetime.time(8, 0)
 datetime.time(8, 15) datetime.time(8, 30) datetime.time(8, 45)
 datetime.time(9, 0) datetime.time(9, 15) datetime.time(9, 30)
 datetime.time(9, 45) datetime.time(10, 0) datetime.time(10, 15)
 datetime.time(10, 30) datetime.time(10, 45) datetime.time(11, 0)
 datetime.time(11, 15) datetime.time(11, 30) datetime.time(11, 45)
 datetime.time(12, 0) datetime.time(12, 15) datetime.time(12, 30)
 datetime.time(12, 45) datetime.time(13, 0) datetime.time(13, 15)
 datetime.time(13, 30) datetime.time(13, 45) datetime.time(14, 0)
 datetime.time(14, 15) datetime.time(14, 30) datetime.time(14, 45)
 datetime.time(15, 0) datetime.time(15, 15) datetime.time(15, 30)
 datetime.time(15, 45) datetime.time(16, 0) datetime.time(16, 15)
 datetime.time(16, 30) datetime.time(16, 45) datetime.time(17, 0)
 datetime.time(17, 15) datetime.time(17, 30) datetime.time(17, 45)
 datetime.time(18, 0) datetime.time(18, 30) datetime.time(18, 45)
 datetime.time(19, 0) datetime.time(19, 15) datetime.time(19, 30)
 datetime.time(19, 45) datetime.time(20, 0) datetime.time(21, 45)
 datetime.time(4, 30) datetime.time(6, 30) datetime.time(18, 15)]

In [45]:
dummy = dt.date(200,1,1)
for element in login_time_df.index:
    dt
    login_time_df["Merged"] = dt.datetime.combine(dummy,login_time_df["Bin"][element])

OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 200-01-01 20:15:00

In [39]:
dt.datetime.combine(dummy,login_time_df["Bin"])

TypeError: combine() argument 2 must be datetime.time, not Series